apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/foos?val
spec:
  ingressClassName: nginx
  rules:
  - host: buse.local
    http:
      paths:
      - path: /api/foos1
        pathType: ImplementationSpecific
        backend:
          service:
            name: java-app-one
            port:
              number: 80
      - path: /api/foos2
        pathType: ImplementationSpecific
        backend:
          service:
            name: java-app-two
            port:
              number: 80
